format = """
$username\
$character in \ 
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$nodejs"""

[character]
success_symbol = '[➜](bold green)'
error_symbol = "[➜](bold red)"

[username]
show_always = true
format="[$user]($style) "

